- name: install frontend
  become: true
  become_user: "{{ appuser }}"
  npm:
    path: "{{ appdir }}"
  tags:
    - bootstrap
    - upgrade

- name: build frontend
  become: true
  become_user: "{{ appuser }}"
  command: npm run build
  args:
    chdir: "{{ appdir }}"
  tags:
    - bootstrap
    - upgrade
