- name: create tlmgr usertree
  become: true
  become_user: zds
  shell: tlmgr init-usertree
  args:
    creates: $HOME/texmf
  tags:
    - bootstrap

- name: create ansible state if non-existant
  file:
    path: "{{ workdir }}/texmf/ansible-state"
    state: touch
    mode: 0666
  tags:
    - bootstrap

- name: check ansible state
  slurp: src="{{ workdir }}/texmf/ansible-state"
  register: installed_packages
  tags:
    - bootstrap

- name: install packages
  become: true
  become_user: zds
  shell: >
    # we make sure that tlmgr repository correspond to texlive annual release
    texlive_year=$(tlmgr --version) &&
    texlive_year=$(echo -n $texlive_year | tail -c 4) &&
    tlmgr option repository http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/$texlive_year/tlnet-final &&
    # we tell updmap to go user mode, not system mode
    updmap-user &&
    # we update and install
    tlmgr update --list &&
    tlmgr install {{ ' '.join(latex_packages) }} &&
    echo {{ ' '.join(latex_packages) }} > $HOME/texmf/ansible-state
  when: installed_packages.content|b64decode|trim != latex_packages|join(" ")
  tags:
    - bootstrap

- name: create tabu directory
  file:
    path: "{{ workdir }}/texmf/tex/latex/tabu/"
    state: directory
  tags:
    - bootstrap

- name: install tabu package
  get_url:
    url: https://raw.githubusercontent.com/tabu-issues-for-future-maintainer/tabu/master/tabu.sty
    dest: "{{ workdir }}/texmf/tex/latex/tabu/tabu.sty"
  tags:
    - bootstrap
