- name: install zmarkdown
  become: true
  become_user: zds
  npm:
    path: "{{ zmarkdown_dir }}"
    production: yes
  notify: restart zmarkdown service
  tags:
    - bootstrap
    - upgrade

- name: add zmarkdown unit file
  template:
    src: zmd.service.j2
    dest: /etc/systemd/system/zmd.service
  notify: restart zmarkdown service
  tags:
    - bootstrap
    - upgrade

- name: start zmarkdown service
  service:
    name: zmd
    state: restarted
    enabled: yes
    daemon_reload: true
  tags:
    - bootstrap
    - upgrade

- name: check that zmarkdown is running
  uri:
    url: http://localhost:27272/
    return_content: yes
  register: this
  delay: 1
  retries: 10
  until: "'zmd is running' in this.content"
  tags:
    - bootstrap
    - upgrade
